version: '3.5'

services:
  cs:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: "cs:latest"
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - pg
    volumes:
      - type: bind
        source: ..
        target: /app
    environment:
      - POSTGRES_PASSWORD=qwer
      - POSTGRES_USER=postgres
    networks:
      - checksystem

  pg:
    image: "postgres:12"
    privileged: true
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql"
    environment:
      - POSTGRES_PASSWORD=qwer
      - POSTGRES_USER=postgres
    networks:
      - checksystem

volumes:
  dbdata:

networks:
  checksystem:
    driver: bridge
