version: "3.8"

services:
  cs:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: cs:latest
    container_name: checksystem
    ports:
      - 8080:8080
    depends_on:
      - pg
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ..
        target: /app
    networks:
      - checksystem

  pg:
    image: postgres:12
    container_name: checksystem_db
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - checksystem

volumes:
  dbdata:

networks:
  checksystem:
    driver: bridge
